chore: add pgvector install instructions
timescale/pgvectorscale pull request #107
Opened 2024-07-05 10:56 UTC by alejandrodnm

When installing from source, pgvector needs to be available; otherwise, the `CREATE EXTENSION vectorscale CASCADE` command will fail. Added a step to check if pgvector is available as the first step in the installation process.

2024-07-05 10:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/pgvectorscale?pullRequest=107) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/pgvectorscale?pullRequest=107) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/pgvectorscale?pullRequest=107) it.</sub>

2024-07-16 18:47 UTC, cevian submitted a review, later dismissed

2024-07-17 17:07 UTC, billy-the-fish requested changes
Nice point, just a couple of small doc thayngs :-).

2024-07-17 17:07 UTC, billy-the-fish commented on README.md
> +  ```sql
The indenting is not working for these steps: https://github.com/timescale/pgvectorscale/blob/1a9c9041104cdabbb2dcfe2c44b79dce1b83f27b/README.md

2024-07-17 17:07 UTC, billy-the-fish commented on README.md
> +
When you have fixed the indenting, the numbering should work again.

2024-07-17 17:07 UTC, billy-the-fish commented on README.md
> +1. Ensure the pgvector extension is available:
Can you move this to after the user connects to the database please. Then the process is:

Build the extension
Connect to database
Check for vector (if no, install)
Enable pgvectorscale

2024-07-25 08:59 UTC, billy-the-fish approved these changes
I've added a couple of thoughts. Looks good.

2024-07-25 08:59 UTC, billy-the-fish commented on README.md
> +On benchmark dataset of 50 million Cohere embeddings (768 dimensions each), PostgreSQL with pgvector and pgvectorscale achieves **28x lower p95 latency** and **16x higher query throughput** compared
```suggestion
On a benchmark dataset of 50 million Cohere embeddings with 768 dimensions each, PostgreSQL with `pgvector` and `pgvectorscale` achieves **28x lower p95 latency** and **16x higher query throughput** compared to Pinecone's storage optimized (s1) index for approximate nearest neighbor queries at 99% recall, all at 75% less cost when self-hosted on AWS EC2.
```

2024-07-25 08:59 UTC, billy-the-fish commented on README.md
> +PostgreSQL with pgvector and pgvectorscale extensions outperformed Pinecone’s storage optimized (s1) and performance-optimized (p2) pod-based index types.
Hmmmmm. Here you are repeating the same words as the last paragraph. I would just remove the line.

2024-07-25 09:02 UTC, alejandrodnm commented on README.md
> +PostgreSQL with pgvector and pgvectorscale extensions outperformed Pinecone’s storage optimized (s1) and performance-optimized (p2) pod-based index types.
I just removed the trailing space 😅  that's why it was part of the PR. I missed that. 

But if you think it's best to remove it. I'll remove it.

2024-07-25 09:04 UTC, billy-the-fish commented on README.md
> +PostgreSQL with pgvector and pgvectorscale extensions outperformed Pinecone’s storage optimized (s1) and performance-optimized (p2) pod-based index types.
Please

2024-08-05 14:01 UTC, jgpruitt approved these changes

2024-08-06 18:15 UTC, cevian approved these changes

2024-08-06 19:18 UTC, merged