Raise diskann maximum dimension from 2K to 16K
timescale/pgvectorscale pull request #181
Opened 2024-12-12 00:14 UTC by tjgreen42

This PR fixes #100 and raises the dimension limit for pgvectorscale's diskann index from 2000 to 16000, which is the maximum supported by the underlying pgvector `vector` type.

The previous limit of 2000 was needed to ensure that all data structures could be serialized onto single 8K pages.  When going beyond 2000 dimensions, so long as SBQ is used for storage, quantized vectors, neighbor lists, and other data structures will still fit on a single page; the only thing that grows too large is `SbqMeans`.  (The raw vectors used for reranking remain in the source relation, where standard Postgres TOAST machinery is used to read/write them). If plain storage is used, the old limit of 2000 remains in place.

To deal with `SbqMeans`, we introduce a `ChainTape` data structure that is similar to `Tape` but supports reads/writes of large buffers across pages.  The chained representation is considered a property of the `PageType`, and we introduce a new `PageType` for `SbqMeans` along with upgrade machinery from the old version.  Similarly to the versioned `MetaPage`, there are no unit tests for this, but I did ad-hoc testing to confirm that the upgrade path works.

2024-12-13 15:31 UTC, syvb requested changes

2024-12-13 15:31 UTC, syvb commented on pgvectorscale/src/util/chain.rs
> +    pub fn write(&mut self, mut data: &[u8]) -> Result<super::ItemPointer> {
This function returns a `anyhow::Result` but always returns `Ok(...)` - why wrap it in a Result? Also why are you using `anyhow` here?

2024-12-13 15:31 UTC, syvb commented on pgvectorscale/src/access_method/build.rs
> +            "Too many dimensions to index without plain storage (max is {}).  Use storag_layout=memory_optimized instead.",
typo
```suggestion
            "Too many dimensions to index without plain storage (max is {}).  Use storage_layout=memory_optimized instead.",
```

2024-12-13 15:31 UTC, syvb commented on pgvectorscale/src/access_method/build.rs
> +            -- generate 300 vectors
It looks like this creates dimensions × 1000 vectors, not 300?

2024-12-13 15:31 UTC, syvb commented on pgvectorscale/src/access_method/sbq.rs
> +pub struct SbqMeans {
I would name this `SbqMeansV2` to avoid confusion when looking at older code that calls something else `SbqMeans`.

2024-12-13 15:31 UTC, syvb commented on pgvectorscale/src/util/tape.rs
> -
It would be better to update `SbqMeans` to `SbqMeansV1` here instead of deleting the whole test.

2024-12-13 20:13 UTC, tjgreen42 commented on pgvectorscale/src/access_method/sbq.rs
> +pub struct SbqMeans {
I'm following the convention here that `MetaPage` uses and which I've also seen in other projects.  Latest version is just called `SbqMeans` which means we don't have to touch code outside of sbq.rs when we bump the version.

2024-12-13 20:16 UTC, tjgreen42 commented on pgvectorscale/src/util/tape.rs
> -
Changing it to `SbqMeansV1` actually breaks the test, because it was relies on implicit knowledge of which page types get instantiated when, and an `SbqMeansV1` page will not have been instantiated at this point.  Meanwhile `SbqMeans` requires a `ChainTape` rather than a regular `Tape` now, and for architectural reasons, I didn't want to put a dependency on `ChainTape` in this file.

2024-12-13 20:24 UTC, tjgreen42 commented on pgvectorscale/src/util/chain.rs
> +    pub fn write(&mut self, mut data: &[u8]) -> Result<super::ItemPointer> {
I agree, let me back this part out.  In an earlier iteration of the PR, I had been more aggressively rewriting various assertions and panics (including in functions this code calls) with the `Result` idiom.  I do think we should do this over time, but I decided to back out those revisions to keep this PR simpler (except it seems for this spot).

2024-12-13 20:31 UTC, tjgreen42 commented on pgvectorscale/src/access_method/build.rs
> +            -- generate 300 vectors
Good catch.  Cut and paste from other test cases that also wrongly say this.

2024-12-16 04:53 UTC, syvb submitted a review, later dismissed

2024-12-16 21:21 UTC, cevian approved these changes
approved but left a few things to think about. Let me know if you decide to change anything and want another review.

2024-12-16 21:21 UTC, cevian commented on pgvectorscale/src/util/chain.rs
> +            let header = ChainItemHeader {
have you considered putting the next pointer inside `TsvPageOpaqueData` instead? If we have a new page type then it's possible to do that. Honestly not 100% sure what's better but wanted to make sure you considered it.

2024-12-16 21:21 UTC, cevian commented on pgvectorscale/src/access_method/sbq.rs
> +                }
not 100% positive I like this interface as opposed to one where the tape_reader has a .buf() function that returns the buffer. The reason: we can later optimize zero-copy for 1-page reads with that interface but not with this one. I'm ok to leave that to future but wanted to point this out

2024-12-16 21:21 UTC, cevian commented on pgvectorscale/src/util/chain.rs
> +                rkyv::from_bytes::<ChainItemHeader>(header_slice).expect("failed to read header");
I don't think this is the zero-copy api would be better to use the zk one. Search the code for archived_root. I think the newer rkyv uses `access`

2024-12-16 21:21 UTC, cevian commented on pgvectorscale/src/util/chain.rs
> +                let data = b"hello world";
better to change the data slightly on each iter

2024-12-16 21:21 UTC, cevian commented on pgvectorscale/src/util/chain.rs
> +        for data_size in BLCKSZ - 100..BLCKSZ + 100 {
nice tests!

2024-12-17 01:53 UTC, tjgreen42 commented on pgvectorscale/src/util/chain.rs
> +            let header = ChainItemHeader {
Yep, I did think about it.  It felt a bit more clunky because the continuation onto another page is really an item-level idea: so even if we had a next-page pointer at the page level, you still need some way to indicate which item spills onto the next page.  Moreover, the next-page pointer only makes sense for some page types.  So I went with the page-pointer being an item-level thing.

2024-12-17 01:56 UTC, tjgreen42 commented on pgvectorscale/src/access_method/sbq.rs
> +                }
That's basically what the tape reader iterator interface is, each `item` has a buf behind it and is zero-copy.  Here we just have a client who is too lazy to deal with things being chunked up like that and copies everything into a client-side buffer.  For meta-data that is read only once during the query, I figured that is fine.

2024-12-17 21:29 UTC, tjgreen42 commented on pgvectorscale/src/util/chain.rs
> +                rkyv::from_bytes::<ChainItemHeader>(header_slice).expect("failed to read header");
Fixed.  At some point soon we should probably bump the `rkyv` version.

2024-12-17 21:32 UTC, tjgreen42 commented on pgvectorscale/src/util/chain.rs
> +            let header = ChainItemHeader {
On reflection, I slightly tweaked the scheme to be a bit more general, such that the item headers now have a full `ItemPointer` payload.  This means that the reader does not have to assume that chasing pointers always leads to the first item on a page, which hides this implementation detail of the writer.  Feels a little smoother this way to me, even if we waste a few more bytes.

2024-12-18 22:35 UTC, cevian approved these changes

2024-12-18 22:36 UTC, merged